# -*- coding: utf-8 -*-
"""03_modelo_rnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_UMd-LM_wmMwzjw_t8OZVIaM9YC7hqd6

# 03_modelo_rnn.ipynb

## Modelo de Red Neuronal Recurrente (RNN) para Predicción de Consumo Eléctrico

**Objetivo:** Entrenar, evaluar y guardar un modelo RNN (SimpleRNN) que prediga la `Global_active_power` (kW) a partir de series temporales multivariadas horarias.

**Pipeline:**
1. Carga del dataset preprocesado (ZIP subido manualmente)
2. Lectura con PySpark → conversión a pandas/numpy
3. Construcción de secuencias temporales (ventanas deslizantes)
4. Arquitectura RNN multivariada
5. Entrenamiento con early stopping y reducción de learning rate
6. Evaluación con MAE, RMSE y R² en el test set
7. Predicciones futuras iterativas (24h y 168h)
8. Persistencia del modelo y métricas para comparación posterior
"""

# -*- coding: utf-8 -*-
# ============================================================
# INSTALACIÓN DE LIBRERÍAS Y CARGA DEL ZIP
# ============================================================

!pip install pyspark findspark tensorflow scikit-learn -q

import findspark
findspark.init()

from pyspark.sql import SparkSession
import pandas as pd
import numpy as np
import json
import os
import zipfile
import pickle
from google.colab import files

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("Subimos el archivo preprocessed_data.zip generado en el notebook 02")
uploaded = files.upload()

"""## 1. Descompresión del ZIP y lectura de datos con PySpark

Se descomprime el archivo subido y se leen los datasets train/validation/test en formato Parquet usando PySpark, cumpliendo con el requisito de Big Data en todo el pipeline. Dado que los datasets agregados por hora tienen ~35,000 filas, se convierten a pandas para el entrenamiento con Keras/TensorFlow sin pérdida de rendimiento.
"""

# ============================================================
# DESCOMPRESIÓN Y LECTURA DE DATOS (AUTO-REPARADOR)
# ============================================================

import os, zipfile, shutil

zip_path = "/content/preprocessed_data.zip"
extract_path = "/content/"

# Descomprimir
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ ZIP descomprimido.")

# --- DIAGNÓSTICO ---
print("\n🔍 Buscando datos preprocesados...")

# Caso 1: existe la carpeta preprocessed_data con los Parquets dentro
if os.path.isdir("/content/preprocessed_data") and os.path.isdir("/content/preprocessed_data/train"):
    data_path = "/content/preprocessed_data"
    print("   Encontrado: /content/preprocessed_data/ (estructura correcta)")

# Caso 2: los archivos quedaron sueltos en /content/
elif os.path.isdir("/content/train") and os.path.isdir("/content/validation"):
    print("   ⚠️ Archivos sueltos detectados en /content/")
    print("   Creando carpeta y moviendo archivos...")

    # Crear carpeta destino
    data_path = "/content/preprocessed_data"
    os.makedirs(data_path, exist_ok=True)

    # Mover cada elemento suelto
    items_to_move = ["train", "validation", "test", "full_hourly",
                     "min_max_scaler.json", "sample_preprocessed.csv"]
    for item in items_to_move:
        src = f"/content/{item}"
        dst = f"{data_path}/{item}"
        if os.path.exists(src):
            shutil.move(src, dst)
            print(f"      → Movido: {item}")

    print("   ✅ Estructura reorganizada.")

else:
    raise FileNotFoundError("❌ No se encontraron los datos preprocesados. Verifica el ZIP subido.")

# Verificar contenido final
print(f"\n📂 Contenido de {data_path}:")
print("   ", os.listdir(data_path))

# ============================================================
# LECTURA CON SPARK
# ============================================================

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("RNN_Model").getOrCreate()

train_spark = spark.read.parquet(f"{data_path}/train")
val_spark   = spark.read.parquet(f"{data_path}/validation")
test_spark  = spark.read.parquet(f"{data_path}/test")

# Convertir a pandas
train_df = train_spark.toPandas()
val_df   = val_spark.toPandas()
test_df  = test_spark.toPandas()

# Cargar parámetros de escalado
import json
with open(f"{data_path}/min_max_scaler.json", "r") as f:
    min_max_dict = json.load(f)

# Ordenar cronológicamente y ELIMINAR NaN de ventanas móviles
for df in [train_df, val_df, test_df]:
    df.sort_values('Datetime', inplace=True)
    df.reset_index(drop=True, inplace=True)
    # ← CORRECCIÓN: eliminar filas con NaN generados por ventanas móviles iniciales
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

print(f"\n📊 Train:      {len(train_df):,} filas (después de dropna)")
print(f"📊 Validation: {len(val_df):,} filas")
print(f"📊 Test:       {len(test_df):,} filas")

print("NaN por dataframe:")
for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    print(f"  {name}: {df.isnull().sum().sum()} valores NaN")

print("\nNaN por columna en train:")
print(train_df.isnull().sum()[train_df.isnull().sum() > 0])

print("\nInfinitos en train:", np.isinf(train_df.select_dtypes(include=[np.number])).sum().sum())

"""## 2. Construcción de secuencias temporales (ventanas deslizantes)

Las redes neuronales recurrentes no reciben una fila aislada, sino una **secuencia de timesteps**. Se define una ventana de `lookback=24` horas para predecir el valor de `Global_active_power` en la hora siguiente.

**Estrategia de features:**
- Todas las variables escaladas (`*_scaled`): garantizan rangos compatibles con activaciones `tanh`.
- Variables cíclicas (`Hour_sin/cos`, `DayOfWeek_sin/cos`, `Month_sin/cos`): capturan periodicidad sin distorsión métrica.
- `IsWeekend`: variable binaria que diferencia patrones de consumo.

La variable objetivo es `Global_active_power_scaled`, que se desescalará posteriormente para interpretar resultados en kW.
"""

# ============================================================
# CREACIÓN DE SECUENCIAS TEMPORALES
# ============================================================

LOOKBACK = 24  # 24 horas de historia → predicción de la hora 25

def create_sequences(df, lookback=24):
    """
    Genera matrices X (samples, lookback, features) e y (samples,)
    a partir de un dataframe ordenado cronológicamente.
    """
    # Seleccionar features: todas las escaladas + cíclicas + IsWeekend
    scaled_cols = [c for c in df.columns if c.endswith('_scaled')]
    cyclic_cols = ['Hour_sin', 'Hour_cos', 'DayOfWeek_sin', 'DayOfWeek_cos',
                   'Month_sin', 'Month_cos']

    feature_cols = sorted(set(scaled_cols + cyclic_cols + ['IsWeekend']))

    # Asegurar que existan todas
    missing = [c for c in feature_cols if c not in df.columns]
    if missing:
        raise ValueError(f"❌ Columnas faltantes: {missing}")

    data = df[feature_cols].values.astype(np.float32)
    target = df['Global_active_power_scaled'].values.astype(np.float32)

    X, y = [], []
    for i in range(len(data) - lookback):
        X.append(data[i : i + lookback])
        y.append(target[i + lookback])

    return np.array(X), np.array(y), feature_cols

X_train, y_train, feature_cols = create_sequences(train_df, LOOKBACK)
X_val,   y_val,   _           = create_sequences(val_df, LOOKBACK)
X_test,  y_test,  _           = create_sequences(test_df, LOOKBACK)

print(f"✅ Secuencias creadas:")
print(f"   X_train: {X_train.shape}  → (samples={X_train.shape[0]}, lookback={X_train.shape[1]}, features={X_train.shape[2]})")
print(f"   y_train: {y_train.shape}")
print(f"   X_val:   {X_val.shape}")
print(f"   X_test:  {X_test.shape}")
print(f"   Features utilizadas: {len(feature_cols)}")

"""## 3. Arquitectura del modelo RNN

Se implementa una red **SimpleRNN** de dos capas como baseline:

| Capa | Tipo | Unidades | Activación | Propósito |
|---|---|---|---|---|
| 1 | SimpleRNN | 64 | tanh | Memoria temporal de corto plazo |
| 2 | Dropout | — | — | Regularización (20%) |
| 3 | SimpleRNN | 32 | tanh | Agregación de patrones profundos |
| 4 | Dropout | — | — | Regularización (20%) |
| 5 | Dense | 16 | relu | Capa intermedia no lineal |
| 6 | Dense | 1 | lineal | Predicción de potencia activa escalada |

**Optimizador:** Adam con learning rate inicial 0.001.  
**Pérdida:** MSE (Mean Squared Error), estándar para regresión.  
**Métrica:** MAE (Mean Absolute Error), interpretable en unidades de la variable objetivo.
"""

# ============================================================
# ARQUITECTURA RNN
# ============================================================

# Fijar semillas para reproducibilidad
tf.random.set_seed(42)
np.random.seed(42)

model_rnn = Sequential([
    SimpleRNN(64, activation='tanh', return_sequences=True,
              input_shape=(LOOKBACK, len(feature_cols))),
    Dropout(0.2),
    SimpleRNN(32, activation='tanh'),
    Dropout(0.2),
    Dense(16, activation='relu'),
    Dense(1)  # Salida lineal: valor escalado de Global_active_power
])

model_rnn.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='mse',
    metrics=['mae']
)

print("=" * 60)
print("ARQUITECTURA RNN")
print("=" * 60)
model_rnn.summary()

"""## 4. Entrenamiento con callbacks

Se configuran tres mecanismos de control durante el entrenamiento:

1. **EarlyStopping**: detiene el entrenamiento si la pérdida de validación no mejora en 10 épocas consecutivas, restaurando los mejores pesos encontrados.
2. **ReduceLROnPlateau**: reduce el learning rate a la mitad si la validación estanca 5 épocas, permitiendo convergencia fina.
3. **ModelCheckpoint**: guarda automáticamente el mejor modelo en disco según `val_loss`.

**Hiperparámetros de entrenamiento:**
- Epochs máximas: 100
- Batch size: 32
- Validación: datos de 2009 (sin fuga temporal)
"""

# ============================================================
# ENTRENAMIENTO
# ============================================================

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=5,
    min_lr=1e-6,
    verbose=1
)

checkpoint = ModelCheckpoint(
    '/content/modelo_rnn_best.h5',
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)

print("🚀 Iniciando entrenamiento RNN...")
history = model_rnn.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=32,
    callbacks=[early_stop, reduce_lr, checkpoint],
    verbose=1
)

print(f"\n✅ Entrenamiento finalizado en época {len(history.history['loss'])}")
print(f"   Mejor val_loss: {min(history.history['val_loss']):.6f}")

"""## 5. Visualización del historial de entrenamiento

Se grafican las curvas de pérdida (MSE) y MAE para detectar sobreajuste, subajuste o convergencia estable.
"""

# ============================================================
# GRÁFICOS DE ENTRENAMIENTO
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

axes[0].plot(history.history['loss'], label='Train MSE', color='steelblue')
axes[0].plot(history.history['val_loss'], label='Val MSE', color='coral')
axes[0].set_title('Evolución de la Pérdida (MSE)')
axes[0].set_xlabel('Época')
axes[0].set_ylabel('MSE')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history.history['mae'], label='Train MAE', color='steelblue')
axes[1].plot(history.history['val_mae'], label='Val MAE', color='coral')
axes[1].set_title('Evolución del MAE')
axes[1].set_xlabel('Época')
axes[1].set_ylabel('MAE')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""## 6. Evaluación en el test set (datos nunca vistos)

Se evalúa el modelo en el conjunto de test (año 2010), que no participó ni en el entrenamiento ni en la validación. Las predicciones se **desescalan** utilizando los parámetros `min` y `max` guardados en el paso 2, para expresar los resultados en kilovatios (kW) con interpretación física directa.

**Métricas:**
- **MAE**: error absoluto medio (robusto a outliers)
- **RMSE**: raíz del error cuadrático medio (penaliza errores grandes)
- **R²**: coeficiente de determinación (capacidad explicativa del modelo)
"""

# ============================================================
# EVALUACIÓN EN TEST SET
# ============================================================

y_pred_scaled = model_rnn.predict(X_test, verbose=0).flatten()

gap_params = min_max_dict['Global_active_power']
gap_min, gap_max = gap_params['min'], gap_params['max']

y_test_kw  = y_test * (gap_max - gap_min) + gap_min
y_pred_kw  = y_pred_scaled * (gap_max - gap_min) + gap_min

mae  = mean_absolute_error(y_test_kw, y_pred_kw)
rmse = np.sqrt(mean_squared_error(y_test_kw, y_pred_kw))
r2   = r2_score(y_test_kw, y_pred_kw)

print("=" * 60)
print("MÉTRICAS DEL MODELO RNN — TEST SET (2010)")
print("=" * 60)
print(f"MAE  : {mae:.4f} kW")
print(f"RMSE : {rmse:.4f} kW")
print(f"R²   : {r2:.4f}")
print("=" * 60)

n_plot = 200
plt.figure(figsize=(14, 5))
plt.plot(y_test_kw[:n_plot], label='Real', linewidth=1.5, color='navy', alpha=0.8)
plt.plot(y_pred_kw[:n_plot], label='Predicho (RNN)', linewidth=1.5, color='crimson', alpha=0.8)
plt.fill_between(range(n_plot), y_test_kw[:n_plot], y_pred_kw[:n_plot],
                 color='gray', alpha=0.15, label='Error')
plt.title(f'RNN: Real vs Predicho — Primeras {n_plot} horas del test set')
plt.xlabel('Horas del test set')
plt.ylabel('Global Active Power (kW)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 6))
plt.scatter(y_test_kw, y_pred_kw, alpha=0.3, s=10, color='teal')
plt.plot([y_test_kw.min(), y_test_kw.max()], [y_test_kw.min(), y_test_kw.max()],
         'k--', lw=2, label='Perfecto')
plt.xlabel('Real (kW)')
plt.ylabel('Predicho (kW)')
plt.title('RNN: Dispersión Real vs Predicho (Test Set)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""## 7. Predicciones futuras (Forecasting)

Se generan predicciones más allá del último dato disponible mediante un esquema **autoregresivo iterativo**:

1. Se toma la última ventana conocida del test set (24 horas).
2. El modelo predice el siguiente timestep.
3. Se actualiza la ventana deslizante incorporando la predicción como nuevo input.
4. Se repite el proceso para 24 horas (1 día) y 168 horas (1 semana).

**Nota metodológica:** En un forecasting real multivariado, las demás variables también deberían proyectarse. Para este ejercicio, se mantienen constantes las variables exógenas y se actualiza únicamente la variable objetivo, lo cual es una aproximación conservadora válida para horizontes cortos.
"""

# ============================================================
# PREDICCIÓN FUTURA ITERATIVA (CORREGIDA)
# ============================================================

def predict_future(model, last_sequence, n_steps, min_max_dict, feature_cols, lookback, start_dt):
    predictions_scaled = []
    current_seq = last_sequence.copy().astype(np.float32)

    gap_min = min_max_dict['Global_active_power']['min']
    gap_max = min_max_dict['Global_active_power']['max']
    target_idx = feature_cols.index('Global_active_power_scaled')

    # Índices de variables cíclicas
    idx_hour_sin = feature_cols.index('Hour_sin')
    idx_hour_cos = feature_cols.index('Hour_cos')
    idx_dow_sin  = feature_cols.index('DayOfWeek_sin')
    idx_dow_cos  = feature_cols.index('DayOfWeek_cos')
    idx_month_sin = feature_cols.index('Month_sin')
    idx_month_cos = feature_cols.index('Month_cos')

    # Índice lag1h (si existe)
    lag1_idx = feature_cols.index('Global_active_power_lag1h_scaled') if 'Global_active_power_lag1h_scaled' in feature_cols else None

    current_dt = pd.to_datetime(start_dt)

    for step in range(n_steps):
        # Predicción del siguiente paso
        pred = model.predict(current_seq.reshape(1, lookback, len(feature_cols)), verbose=0)
        pred_val = pred[0, 0]
        predictions_scaled.append(pred_val)

        # Avanzar 1 hora en el calendario
        current_dt += pd.Timedelta(hours=1)
        h = current_dt.hour
        # Spark dayofweek: 1=Domingo, 7=Sábado
        dow = (current_dt.weekday() + 2) % 7
        if dow == 0:
            dow = 7
        m = current_dt.month

        # Crear nuevo timestep actualizando cíclicas y objetivo
        new_step = current_seq[-1].copy()
        new_step[target_idx] = pred_val

        # ← CORRECCIÓN CLAVE: actualizar variables cíclicas con la hora/día/mes FUTURO
        new_step[idx_hour_sin] = np.sin(2 * np.pi * h / 24)
        new_step[idx_hour_cos] = np.cos(2 * np.pi * h / 24)
        new_step[idx_dow_sin]  = np.sin(2 * np.pi * (dow - 1) / 7)
        new_step[idx_dow_cos]  = np.cos(2 * np.pi * (dow - 1) / 7)
        new_step[idx_month_sin] = np.sin(2 * np.pi * (m - 1) / 12)
        new_step[idx_month_cos] = np.cos(2 * np.pi * (m - 1) / 12)

        # Actualizar lag1h con la predicción reciente
        if lag1_idx is not None:
            new_step[lag1_idx] = pred_val

        # Desplazar ventana
        current_seq = np.roll(current_seq, -1, axis=0)
        current_seq[-1] = new_step

    # Desescalar a kW
    return np.array(predictions_scaled) * (gap_max - gap_min) + gap_min


# Última ventana del test set
last_window = X_test[-1].copy()

# ← CORRECCIÓN: pasar el último timestamp real del test como punto de partida
start_time = pd.to_datetime(test_df['Datetime'].iloc[-1])

# Predicciones
pred_24h  = predict_future(model_rnn, last_window, 24,  min_max_dict, feature_cols, LOOKBACK, start_time)
pred_168h = predict_future(model_rnn, last_window, 168, min_max_dict, feature_cols, LOOKBACK, start_time)

print("=" * 60)
print("PREDICCIONES FUTURAS — RNN (CORREGIDO)")
print("=" * 60)
print(f"Próximas 24 horas:")
print(f"   Media: {pred_24h.mean():.3f} kW | Mín: {pred_24h.min():.3f} kW | Máx: {pred_24h.max():.3f} kW")
print(f"Próximas 168 horas:")
print(f"   Media: {pred_168h.mean():.3f} kW | Mín: {pred_168h.min():.3f} kW | Máx: {pred_168h.max():.3f} kW")

# Gráfico 24h
plt.figure(figsize=(12, 4))
plt.plot(range(1, 25), pred_24h, marker='o', markersize=5, color='darkorange', linewidth=2)
plt.axhline(y=pred_24h.mean(), color='gray', linestyle='--', alpha=0.7, label=f'Media={pred_24h.mean():.2f} kW')
plt.title('RNN: Predicción de consumo — Próximas 24 horas')
plt.xlabel('Horas futuras')
plt.ylabel('Global Active Power (kW)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Gráfico 168h (1 semana)
plt.figure(figsize=(14, 4))
plt.plot(range(1, 169), pred_168h, color='teal', linewidth=1.5, alpha=0.9)
plt.axhline(y=pred_168h.mean(), color='gray', linestyle='--', alpha=0.7, label=f'Media={pred_168h.mean():.2f} kW')
plt.title('RNN: Predicción de consumo — Próxima semana (168 horas)')
plt.xlabel('Horas futuras')
plt.ylabel('Global Active Power (kW)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Guardar predicciones corregidas
np.save('/content/pred_rnn_24h.npy', pred_24h)
np.save('/content/pred_rnn_168h.npy', pred_168h)
print("\n✅ Predicciones corregidas guardadas")
files.download('/content/pred_rnn_24h.npy')
files.download('/content/pred_rnn_168h.npy')

"""## 8. Guardado del modelo y artefactos

Se persisten los siguientes entregables para el notebook de comparación (`06_comparacion_modelos.ipynb`) y el dashboard de Streamlit:

| Archivo | Formato | Uso |
|---|---|---|
| `modelo_rnn_final.keras` | Keras nativo | Carga del modelo en Streamlit |
| `metrics_rnn.json` | JSON | Tabla comparativa de modelos |
| `history_rnn.pkl` | Pickle | Gráficos de convergencia en el dashboard |
| `pred_rnn_24h.npy` / `168h.npy` | NumPy | Series de predicción futura para visualización |
"""

# ============================================================
# GUARDADO DE MODELO Y ARTEFACTOS
# ============================================================

model_rnn.save('/content/modelo_rnn_final.keras')
print("✅ Modelo guardado: /content/modelo_rnn_final.keras")

with open('/content/history_rnn.pkl', 'wb') as f:
    pickle.dump(history.history, f)
print("✅ Historia guardada: /content/history_rnn.pkl")

metrics_rnn = {
    'modelo': 'RNN',
    'mae': float(mae),
    'rmse': float(rmse),
    'r2': float(r2),
    'lookback': LOOKBACK,
    'epochs_trained': len(history.history['loss']),
    'best_val_loss': float(min(history.history['val_loss']))
}
with open('/content/metrics_rnn.json', 'w') as f:
    json.dump(metrics_rnn, f, indent=2)
print("✅ Métricas guardadas: /content/metrics_rnn.json")

np.save('/content/pred_rnn_24h.npy', pred_24h)
np.save('/content/pred_rnn_168h.npy', pred_168h)
print("✅ Predicciones futuras guardadas")

print("\n📥 Iniciando descargas...")
files.download('/content/modelo_rnn_final.keras')
files.download('/content/metrics_rnn.json')
files.download('/content/history_rnn.pkl')
files.download('/content/pred_rnn_24h.npy')
files.download('/content/pred_rnn_168h.npy')

"""## Justificación técnica del modelo RNN

Se selecciona una **Red Neuronal Recurrente (SimpleRNN)** como baseline del proyecto por las siguientes razones:

1. **Memoria temporal explícita**: A diferencia de redes densas tradicionales, las RNN mantienen un estado oculto que se propaga a través de la secuencia, permitiendo capturar dependencias temporales en el consumo eléctrico (inercia térmica, hábitos de uso).

2. **Baseline interpretable**: SimpleRNN es la arquitectura recurrente más elemental. Si LSTM o GRU superan significativamente sus métricas, se demuestra cuantitativamente que el problema requiere mecanismos de compuertas (olvido/control de flujo) más sofisticados.

3. **Entrada multivariada**: En cada paso de tiempo, el modelo recibe un vector con todas las variables predictoras escaladas (potencias, voltaje, submediciones, medias móviles, diferencias) junto con codificaciones cíclicas, permitiendo aprender interacciones no lineales entre predictores.

4. **Regularización**: Las capas `Dropout(0.2)` mitigan el sobreajuste en un dataset de ~35,000 registros horarios, forzando al modelo a aprender representaciones robustas.

5. **Optimización adaptativa**: `ReduceLROnPlateau` ajusta dinámicamente la tasa de aprendizaje cuando la validación estanca, evitando oscilaciones alrededor del mínimo.

6. **Forecasting autoregresivo**: Las predicciones futuras se generan iterativamente, reinyectando cada predicción como input del siguiente paso. Este esquema simula condiciones reales de despliegue donde no se dispone de valores futuros observados.

**Limitaciones conocidas**: SimpleRNN puede sufrir del problema de *vanishing gradients* en secuencias largas. Si el modelo no captura dependencias de largo plazo (ej. estacionalidad anual), LSTM/GRU deberían mejorar el R² sustancialmente, lo cual se verificará en los notebooks 04 y 05.
"""