# -*- coding: utf-8 -*-
"""05_modelo_gru.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utDfuojhZkdDTOvOZ1MJsb0S1zRj1Eqq

# 05_modelo_gru.ipynb

## Modelo GRU para Predicción de Consumo Eléctrico

**Objetivo:** Entrenar, evaluar y guardar un modelo **GRU (Gated Recurrent Unit)** que prediga la `Global_active_power` (kW) a partir de series temporales multivariadas horarias.

**Diferencia con LSTM:** GRU simplifica la arquitectura de compuertas de LSTM fusionando el cell state y el hidden state en un único estado oculto, utilizando solo dos compuertas (update y reset) en lugar de tres. Esto reduce el número de parámetros y acelera el entrenamiento, manteniendo una capacidad comparable para capturar dependencias de largo plazo.

**Pipeline:**
1. Carga del dataset preprocesado (ZIP subido manualmente)
2. Lectura con PySpark → conversión a pandas/numpy
3. Construcción de secuencias temporales (ventanas deslizantes)
4. Arquitectura GRU multivariada
5. Entrenamiento con early stopping y reducción de learning rate
6. Evaluación con MAE, RMSE y R² en el test set
7. Predicciones futuras iterativas (24h y 168h) con actualización de variables cíclicas
8. Persistencia del modelo y métricas para comparación posterior
"""

# -*- coding: utf-8 -*-
# ============================================================
# INSTALACIÓN DE LIBRERÍAS Y CARGA DEL ZIP
# ============================================================

!pip install pyspark findspark tensorflow scikit-learn -q

import findspark
findspark.init()

from pyspark.sql import SparkSession
import pandas as pd
import numpy as np
import json
import os
import zipfile
import pickle
import shutil
from google.colab import files

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("📤 Sube el archivo preprocessed_data.zip generado en el notebook 02")
uploaded = files.upload()

"""## 1. Descompresión del ZIP y lectura de datos con PySpark

Se descomprime el archivo subido y se leen los datasets train/validation/test en formato Parquet usando PySpark. El pipeline mantiene el requisito de Big Data en todas las etapas de lectura y agregación.
"""

# ============================================================
# DESCOMPRESIÓN Y LECTURA DE DATOS (AUTO-REPARADOR)
# ============================================================

zip_path = "/content/preprocessed_data.zip"
extract_path = "/content/"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ ZIP descomprimido.")

# --- DIAGNÓSTICO ---
print("\n🔍 Buscando datos preprocesados...")

if os.path.isdir("/content/preprocessed_data") and os.path.isdir("/content/preprocessed_data/train"):
    data_path = "/content/preprocessed_data"
    print("   Encontrado: /content/preprocessed_data/ (estructura correcta)")

elif os.path.isdir("/content/train") and os.path.isdir("/content/validation"):
    print("   ⚠️ Archivos sueltos detectados en /content/")
    print("   Creando carpeta y moviendo archivos...")

    data_path = "/content/preprocessed_data"
    os.makedirs(data_path, exist_ok=True)

    items_to_move = ["train", "validation", "test", "full_hourly",
                     "min_max_scaler.json", "sample_preprocessed.csv"]
    for item in items_to_move:
        src = f"/content/{item}"
        dst = f"{data_path}/{item}"
        if os.path.exists(src):
            shutil.move(src, dst)
            print(f"      → Movido: {item}")

    print("   ✅ Estructura reorganizada.")
else:
    raise FileNotFoundError("❌ No se encontraron los datos preprocesados. Verifica el ZIP subido.")

print(f"\n📂 Contenido de {data_path}:")
print("   ", os.listdir(data_path))

# ============================================================
# LECTURA CON SPARK
# ============================================================

spark = SparkSession.builder.appName("GRU_Model").getOrCreate()

train_spark = spark.read.parquet(f"{data_path}/train")
val_spark   = spark.read.parquet(f"{data_path}/validation")
test_spark  = spark.read.parquet(f"{data_path}/test")

# Convertir a pandas
train_df = train_spark.toPandas()
val_df   = val_spark.toPandas()
test_df  = test_spark.toPandas()

# Cargar parámetros de escalado
with open(f"{data_path}/min_max_scaler.json", "r") as f:
    min_max_dict = json.load(f)

# Ordenar cronológicamente y eliminar NaN residuales
for df in [train_df, val_df, test_df]:
    df.sort_values('Datetime', inplace=True)
    df.reset_index(drop=True, inplace=True)
    df.dropna(inplace=True)
    df.reset_index(drop=True, inplace=True)

print(f"\n📊 Train:      {len(train_df):,} filas | {train_df['Datetime'].min()} → {train_df['Datetime'].max()}")
print(f"📊 Validation: {len(val_df):,} filas | {val_df['Datetime'].min()} → {val_df['Datetime'].max()}")
print(f"📊 Test:       {len(test_df):,} filas | {test_df['Datetime'].min()} → {test_df['Datetime'].max()}")
print(f"📐 Features disponibles: {len(train_df.columns)} columnas")

# Verificación post-limpieza
print("\n🔍 Verificación post-dropna:")
for name, df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    print(f"  {name}: {df.isnull().sum().sum()} NaN restantes")

"""## 2. Construcción de secuencias temporales (ventanas deslizantes)

Las redes GRU reciben tensores 3D: `(samples, timesteps, features)`. Se mantiene `lookback=24` horas para predecir la siguiente hora, garantizando comparabilidad directa con los modelos RNN y LSTM.

**Features de entrada:**
- Variables escaladas (`*_scaled`)
- Codificaciones cíclicas (`Hour_sin/cos`, `DayOfWeek_sin/cos`, `Month_sin/cos`)
- Variable binaria `IsWeekend`

La variable objetivo es `Global_active_power_scaled`.
"""

# ============================================================
# CREACIÓN DE SECUENCIAS TEMPORALES
# ============================================================

LOOKBACK = 24  # 24 horas de historia → predicción de la hora 25

def create_sequences(df, lookback=24):
    scaled_cols = [c for c in df.columns if c.endswith('_scaled')]
    cyclic_cols = ['Hour_sin', 'Hour_cos', 'DayOfWeek_sin', 'DayOfWeek_cos',
                   'Month_sin', 'Month_cos']

    feature_cols = sorted(set(scaled_cols + cyclic_cols + ['IsWeekend']))

    missing = [c for c in feature_cols if c not in df.columns]
    if missing:
        raise ValueError(f"❌ Columnas faltantes: {missing}")

    data = df[feature_cols].values.astype(np.float32)
    target = df['Global_active_power_scaled'].values.astype(np.float32)

    X, y = [], []
    for i in range(len(data) - lookback):
        X.append(data[i : i + lookback])
        y.append(target[i + lookback])

    return np.array(X), np.array(y), feature_cols

X_train, y_train, feature_cols = create_sequences(train_df, LOOKBACK)
X_val,   y_val,   _           = create_sequences(val_df, LOOKBACK)
X_test,  y_test,  _           = create_sequences(test_df, LOOKBACK)

print(f"✅ Secuencias creadas:")
print(f"   X_train: {X_train.shape}")
print(f"   y_train: {y_train.shape}")
print(f"   X_val:   {X_val.shape}")
print(f"   X_test:  {X_test.shape}")
print(f"   Features: {len(feature_cols)}")

"""## 3. Arquitectura del modelo GRU

Se implementa una red **GRU** de dos capas con dropout:

| Capa | Tipo | Unidades | Activación | Propósito |
|---|---|---|---|---|
| 1 | GRU | 64 | tanh | Captura de dependencias temporales con compuertas update/reset |
| 2 | Dropout | — | — | Regularización (20%) |
| 3 | GRU | 32 | tanh | Refinamiento de patrones profundos |
| 4 | Dropout | — | — | Regularización (20%) |
| 5 | Dense | 16 | relu | Capa intermedia no lineal |
| 6 | Dense | 1 | lineal | Predicción de potencia activa escalada |

**Optimizador:** Adam (lr=0.001).  
**Pérdida:** MSE.  
**Métrica:** MAE.

GRU fusiona el cell state y hidden state de LSTM en un único vector de estado, reduciendo la complejidad paramétrica sin sacrificar capacidad de modelado en series temporales con ciclos claros.
"""

# ============================================================
# ARQUITECTURA GRU
# ============================================================

tf.random.set_seed(42)
np.random.seed(42)

model_gru = Sequential([
    GRU(64, activation='tanh', return_sequences=True,
        input_shape=(LOOKBACK, len(feature_cols))),
    Dropout(0.2),
    GRU(32, activation='tanh'),
    Dropout(0.2),
    Dense(16, activation='relu'),
    Dense(1)
])

model_gru.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='mse',
    metrics=['mae']
)

print("=" * 60)
print("ARQUITECTURA GRU")
print("=" * 60)
model_gru.summary()

"""## 4. Entrenamiento con callbacks

Mismos mecanismos de control que RNN y LSTM para garantizar comparabilidad estricta:
- **EarlyStopping**: paciencia 10 épocas, restaura mejores pesos.
- **ReduceLROnPlateau**: reduce lr a la mitad si estanca 5 épocas.
- **ModelCheckpoint**: guarda el mejor modelo por `val_loss`.

**Hiperparámetros:**
- Epochs máximas: 100
- Batch size: 32
- Validación: año 2009
"""

# ============================================================
# ENTRENAMIENTO
# ============================================================

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=5,
    min_lr=1e-6,
    verbose=1
)

checkpoint = ModelCheckpoint(
    '/content/modelo_gru_best.h5',
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)

print("🚀 Iniciando entrenamiento GRU...")
history = model_gru.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=32,
    callbacks=[early_stop, reduce_lr, checkpoint],
    verbose=1
)

print(f"\n✅ Entrenamiento finalizado en época {len(history.history['loss'])}")
print(f"   Mejor val_loss: {min(history.history['val_loss']):.6f}")

"""## 5. Visualización del historial de entrenamiento

Curvas de pérdida (MSE) y MAE para comparar convergencia y detectar sobreajuste.
"""

# ============================================================
# GRÁFICOS DE ENTRENAMIENTO
# ============================================================

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

axes[0].plot(history.history['loss'], label='Train MSE', color='steelblue')
axes[0].plot(history.history['val_loss'], label='Val MSE', color='coral')
axes[0].set_title('Evolución de la Pérdida (MSE) — GRU')
axes[0].set_xlabel('Época')
axes[0].set_ylabel('MSE')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(history.history['mae'], label='Train MAE', color='steelblue')
axes[1].plot(history.history['val_mae'], label='Val MAE', color='coral')
axes[1].set_title('Evolución del MAE — GRU')
axes[1].set_xlabel('Época')
axes[1].set_ylabel('MAE')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""## 6. Evaluación en el test set (datos nunca vistos)

Evaluación en 2010 con desescalado a kW para interpretación física directa. Se calculan MAE, RMSE y R² para la tabla comparativa del notebook 06.
"""

# ============================================================
# EVALUACIÓN EN TEST SET
# ============================================================

y_pred_scaled = model_gru.predict(X_test, verbose=0).flatten()

gap_params = min_max_dict['Global_active_power']
gap_min, gap_max = gap_params['min'], gap_params['max']

y_test_kw  = y_test * (gap_max - gap_min) + gap_min
y_pred_kw  = y_pred_scaled * (gap_max - gap_min) + gap_min

mae  = mean_absolute_error(y_test_kw, y_pred_kw)
rmse = np.sqrt(mean_squared_error(y_test_kw, y_pred_kw))
r2   = r2_score(y_test_kw, y_pred_kw)

print("=" * 60)
print("MÉTRICAS DEL MODELO GRU — TEST SET (2010)")
print("=" * 60)
print(f"MAE  : {mae:.4f} kW")
print(f"RMSE : {rmse:.4f} kW")
print(f"R²   : {r2:.4f}")
print("=" * 60)

n_plot = 200
plt.figure(figsize=(14, 5))
plt.plot(y_test_kw[:n_plot], label='Real', linewidth=1.5, color='navy', alpha=0.8)
plt.plot(y_pred_kw[:n_plot], label='Predicho (GRU)', linewidth=1.5, color='crimson', alpha=0.8)
plt.fill_between(range(n_plot), y_test_kw[:n_plot], y_pred_kw[:n_plot],
                 color='gray', alpha=0.15, label='Error')
plt.title(f'GRU: Real vs Predicho — Primeras {n_plot} horas del test set')
plt.xlabel('Horas del test set')
plt.ylabel('Global Active Power (kW)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 6))
plt.scatter(y_test_kw, y_pred_kw, alpha=0.3, s=10, color='teal')
plt.plot([y_test_kw.min(), y_test_kw.max()], [y_test_kw.min(), y_test_kw.max()],
         'k--', lw=2, label='Perfecto')
plt.xlabel('Real (kW)')
plt.ylabel('Predicho (kW)')
plt.title('GRU: Dispersión Real vs Predicho (Test Set)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""## 7. Predicciones futuras (Forecasting)

Predicciones autoregresivas con **actualización de variables cíclicas** (hora, día de semana, mes) para evitar el colapso a la media. Se proyectan 24h y 168h.
"""

# ============================================================
# PREDICCIÓN FUTURA ITERATIVA (CON CORRECCIÓN CÍCLICA)
# ============================================================

def predict_future(model, last_sequence, n_steps, min_max_dict, feature_cols, lookback, start_dt):
    predictions_scaled = []
    current_seq = last_sequence.copy().astype(np.float32)

    gap_min = min_max_dict['Global_active_power']['min']
    gap_max = min_max_dict['Global_active_power']['max']
    target_idx = feature_cols.index('Global_active_power_scaled')

    idx_hour_sin = feature_cols.index('Hour_sin')
    idx_hour_cos = feature_cols.index('Hour_cos')
    idx_dow_sin  = feature_cols.index('DayOfWeek_sin')
    idx_dow_cos  = feature_cols.index('DayOfWeek_cos')
    idx_month_sin = feature_cols.index('Month_sin')
    idx_month_cos = feature_cols.index('Month_cos')

    lag1_idx = feature_cols.index('Global_active_power_lag1h_scaled') if 'Global_active_power_lag1h_scaled' in feature_cols else None

    current_dt = pd.to_datetime(start_dt)

    for step in range(n_steps):
        pred = model.predict(current_seq.reshape(1, lookback, len(feature_cols)), verbose=0)
        pred_val = pred[0, 0]
        predictions_scaled.append(pred_val)

        current_dt += pd.Timedelta(hours=1)
        h = current_dt.hour
        dow = (current_dt.weekday() + 2) % 7
        if dow == 0:
            dow = 7
        m = current_dt.month

        new_step = current_seq[-1].copy()
        new_step[target_idx] = pred_val

        new_step[idx_hour_sin] = np.sin(2 * np.pi * h / 24)
        new_step[idx_hour_cos] = np.cos(2 * np.pi * h / 24)
        new_step[idx_dow_sin]  = np.sin(2 * np.pi * (dow - 1) / 7)
        new_step[idx_dow_cos]  = np.cos(2 * np.pi * (dow - 1) / 7)
        new_step[idx_month_sin] = np.sin(2 * np.pi * (m - 1) / 12)
        new_step[idx_month_cos] = np.cos(2 * np.pi * (m - 1) / 12)

        if lag1_idx is not None:
            new_step[lag1_idx] = pred_val

        current_seq = np.roll(current_seq, -1, axis=0)
        current_seq[-1] = new_step

    return np.array(predictions_scaled) * (gap_max - gap_min) + gap_min


last_window = X_test[-1].copy()
start_time = pd.to_datetime(test_df['Datetime'].iloc[-1])

pred_24h  = predict_future(model_gru, last_window, 24,  min_max_dict, feature_cols, LOOKBACK, start_time)
pred_168h = predict_future(model_gru, last_window, 168, min_max_dict, feature_cols, LOOKBACK, start_time)

print("=" * 60)
print("PREDICCIONES FUTURAS — GRU")
print("=" * 60)
print(f"Próximas 24 horas:")
print(f"   Media: {pred_24h.mean():.3f} kW | Mín: {pred_24h.min():.3f} kW | Máx: {pred_24h.max():.3f} kW")
print(f"Próximas 168 horas:")
print(f"   Media: {pred_168h.mean():.3f} kW | Mín: {pred_168h.min():.3f} kW | Máx: {pred_168h.max():.3f} kW")

plt.figure(figsize=(12, 4))
plt.plot(range(1, 25), pred_24h, marker='o', markersize=5, color='darkorange', linewidth=2)
plt.axhline(y=pred_24h.mean(), color='gray', linestyle='--', alpha=0.7, label=f'Media={pred_24h.mean():.2f} kW')
plt.title('GRU: Predicción de consumo — Próximas 24 horas')
plt.xlabel('Horas futuras')
plt.ylabel('Global Active Power (kW)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

plt.figure(figsize=(14, 4))
plt.plot(range(1, 169), pred_168h, color='teal', linewidth=1.5, alpha=0.9)
plt.axhline(y=pred_168h.mean(), color='gray', linestyle='--', alpha=0.7, label=f'Media={pred_168h.mean():.2f} kW')
plt.title('GRU: Predicción de consumo — Próxima semana (168 horas)')
plt.xlabel('Horas futuras')
plt.ylabel('Global Active Power (kW)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""## 8. Guardado del modelo y artefactos

Se persisten los entregables para el notebook 06 y el dashboard de Streamlit:

| Archivo | Formato | Uso |
|---|---|---|
| `modelo_gru_final.keras` | Keras nativo | Carga en Streamlit |
| `metrics_gru.json` | JSON | Tabla comparativa 06 |
| `history_gru.pkl` | Pickle | Gráficos de convergencia |
| `pred_gru_24h.npy` / `168h.npy` | NumPy | Predicciones futuras en dashboard |
"""

# ============================================================
# GUARDADO DE MODELO Y ARTEFACTOS
# ============================================================

model_gru.save('/content/modelo_gru_final.keras')
print("✅ Modelo guardado: /content/modelo_gru_final.keras")

with open('/content/history_gru.pkl', 'wb') as f:
    pickle.dump(history.history, f)
print("✅ Historia guardada: /content/history_gru.pkl")

metrics_gru = {
    'modelo': 'GRU',
    'mae': float(mae),
    'rmse': float(rmse),
    'r2': float(r2),
    'lookback': LOOKBACK,
    'epochs_trained': len(history.history['loss']),
    'best_val_loss': float(min(history.history['val_loss']))
}
with open('/content/metrics_gru.json', 'w') as f:
    json.dump(metrics_gru, f, indent=2)
print("✅ Métricas guardadas: /content/metrics_gru.json")

np.save('/content/pred_gru_24h.npy', pred_24h)
np.save('/content/pred_gru_168h.npy', pred_168h)
print("✅ Predicciones futuras guardadas")

print("\n📥 Iniciando descargas...")
files.download('/content/modelo_gru_final.keras')
files.download('/content/metrics_gru.json')
files.download('/content/history_gru.pkl')
files.download('/content/pred_gru_24h.npy')
files.download('/content/pred_gru_168h.npy')

"""## Justificación técnica del modelo GRU

Se selecciona **GRU** como tercera arquitectura por las siguientes razones:

1. **Eficiencia paramétrica**: GRU tiene aproximadamente un 25-30% menos de parámetros que LSTM al fusionar el cell state y hidden state en un único vector. Esto reduce el tiempo de entrenamiento y la memoria requerida, siendo ideal para datasets de tamaño medio como el actual (~35,000 registros horarios).

2. **Capacidad de modelado comparable**: Aunque más simple, las compuertas de actualización (update gate) y reinicio (reset gate) de GRU permiten capturar dependencias de largo plazo con eficacia similar a LSTM en problemas donde los ciclos temporales son claros y estables (como el consumo eléctrico residencial).

3. **Comparabilidad controlada**: Se mantienen idénticos los hiperparámetros de entrenamiento (epochs, batch size, callbacks, lookback) y el pipeline de features respecto a RNN y LSTM. Cualquier diferencia en métricas se atribuye exclusivamente a la arquitectura.

4. **Trade-off velocidad-precisión**: GRU ofrece un punto intermedio entre la simplicidad de RNN (rápida pero limitada) y la complejidad de LSTM (potente pero más pesada). Si GRU alcanza métricas similares a LSTM con menor costo computacional, demuestra que el problema no requiere la sobrecarga paramétrica de tres compuertas.

**Hipótesis esperada**: GRU debería obtener métricas intermedias entre RNN y LSTM, o muy cercanas a LSTM, validando que el consumo eléctrico es un problema donde la eficiencia paramétrica puede compensar la menor complejidad de compuertas.
"""